### PR TITLE
Update fixing for symbol-sdk and symbol-hd-wallets

### PR DESCRIPTION
**Pull request by 44uk**
Update to latest SDK and wallets library. But still need fixing for new Address format.

### CODE REVIEW

**Comment by decentraliser** [comment]
Sweet @44uk ! Thanks!
Do you want to update the address format or you want me to have a look at it?

**Comment by 44uk** [comment]
@decentraliser added fixing for new address format. Please review it!

**Comment by 44uk** [comment]
I notice a problem that new address format has static postfixed character. It must be one of I, A, Q, Y, because of checksum. Do you have any idea?

**Comment by decentraliser** [comment]
hi! Does the address lenght fixes the checksum issue?

**Comment by decentraliser** [comment]
I'm looking at it, for some reason I can't use the mnemonic in symbol-desktop-wallet

**Comment by decentraliser** [comment]
oh no lol, looks good! thanks a lot!

**Pull request merged**
